kind: ConfigMap
apiVersion: v1
metadata:
  name: local-lvm-config
  namespace: local-lvm-storage
data:
  config.json: |-
        {
                "nodeVGMap":[
                {
                        "node":"DEFAULT_VGS_FOR_NON_LISTED_NODES",
                        "vgs":["vg1"]
                },
                {
                        "node":"yasker-lp-dev1",
                        "vgs":["vg0", "vg1"]
                },
                {
                        "node":"yasker-lp-dev3",
                        "vgs":[]
                }
                ]
        }

