apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: local-lvm-provisioner
  namespace: local-lvm-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-lvm-provisioner
  template:
    metadata:
      labels:
        app: local-lvm-provisioner
    spec:
      serviceAccountName: local-lvm-provisioner-service-account
      containers:
      - name: local-lvm-provisioner
        image: @REPO@/local-lvm-provisioner:@TAG@
        imagePullPolicy: Always
        args:
        - run
        - --debug
        - start
        - --config
        - /etc/config/config.json
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config/
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
        - name: config-volume
          configMap:
            name: local-lvm-config
