apiVersion: v1
kind: Pod
metadata:
  name: local-lvm-test
  labels:
    app.kubernetes.io/name: local-lvm-test
spec:
  containers:
    - name: test
      # Jenkins image used for illustration purposes because it has a user
      # with uid=1000 and gid=1000 that matches the specified security context
      image: jenkins/jenkins
      command:
        - /config/test.sh
      volumeMounts:
        - name: test
          mountPath: /test
        - name: config
          mountPath: /config
  restartPolicy: Never
  securityContext:
    fsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  terminationGracePeriodSeconds: 0
  volumes:
    - name: test
      persistentVolumeClaim:
        claimName: local-lvm-pvc
    - name: config
      configMap:
        name: local-lvm-test
        defaultMode: 0555
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-lvm-test
  labels:
    app.kubernetes.io/name: local-lvm-test
data:
  test.sh: |
    #!/bin/sh
    id
    ls -al /test && \
    echo 'Hello from local-lvm-test' && \
    cp /config/text.txt /test/test.txt && \
    touch /test/foo && \
    ls -al /test
  text.txt: |
    some test content
